### ISSUE TITLE
Fix Facebook Snippets

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#13]
Facebook posts aren't pulling in editorial text 

![screen shot 2015-01-22 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/10623537/5867086/b05dee56-a24c-11e4-8286-b7447b2f61b7.png)

**Comment by 600lines** [comment]
Fixed

**Comment by JoannaIHC** [comment]
Looks good thanks!
