### ISSUE TITLE
Google Analytics - Clean Up

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#16]
Include the Hostname to the Request URI
Set default page so no "/" shows up in the rows 
Filter bot traffic (ghost referrals: darodar, iloveitaly, semalt, buttons-for-website.com, etc)
Make sure we exclude traffic to Preview pages + any other testing environment (if one exists)
Filter unnecessary query parameters
Separate mobile and non-mobile traffic
Make sure we have lowercase filters set up
Exclude employee IP addresses from reports
Capture SEO metrics + referral keywords from organic search
Set up any Ecommerce data from the shop
Turn on Site Search tracking

Is it possible to include any metrics from from ticket link sales?

**Comment by 600lines** [comment]
A lot of this can be curbed from SEO settings on WP to turn off crawling/analytics. I'm going to jump in on this with you tomorrow 2/6/15.
