### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#19]
Create http://iheartcomix.com/events/      >    http://iheartcomix.com/upcoming-events/    

Create http://iheartcomix.com/store    >     http://shop.hyvcollective.com/collections/iheartcomix

**Comment by 600lines** [comment]
Iheartcomix.com/events is now just being used. upcoming-events will not be working anymore. 
http://iheartcomix.com/store created, and redirects. updated all menus
