### ISSUE TITLE
Fix Date Field on Event Page Template

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#20]
The current event page doesn't let you put in a date for the show. You have to publish the page and then after it's live go back and change the Publish Date field to whatever the actual day of show is in order to have it appear live. Please create a new and separate "Day of Show" field to populate

**Comment by 600lines** [comment]
This won't work since it's a much easier to display the events in Descending order with date tag. You can actually update the date and backdate it before you publish live. The site is tagged to be able to publish future posts, and not schedule them.
