### ISSUE TITLE
404 Page in Top Ten Content

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#25]
Keep seeing a 404 in the top 10 pages in Analytics - can you please investigate? (also what is Co.Lumb?)

![screen shot 2015-01-28 at 9 51 02 pm](https://cloud.githubusercontent.com/assets/10623537/5953056/edb85be8-a737-11e4-8f95-d49616f248e3.png)

**Comment by 600lines** [comment]
I wouldn't worry about this - probably outdated posts or old RSVPs hitting the 404. Afer some research co.lumb is some spam from Russia like a gateway. Don't worry about this either.
