### ISSUE TITLE
Wordpress Visual Mode formatting not translating to Live 

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#26]
In the blog template formatting is not appearing the same when published

Can we fix so backend is picking up spacing in the html

![wp2](https://cloud.githubusercontent.com/assets/10623537/5981757/d8e0a334-a871-11e4-9341-47440f5e9d8d.png)
![wp1](https://cloud.githubusercontent.com/assets/10623537/5981756/d8dee152-a871-11e4-8a40-e97400ffbbc6.png)

**Comment by 600lines** [comment]
This actually works, but if you check out the code by clicking the "Text" tab next to "visual" you'll see that there are <div> tags in the code. 

![image](https://cloud.githubusercontent.com/assets/9582334/6076850/6f749050-ad9d-11e4-8e82-a6426ff0841f.png)

This tends to happen when you copy and paste content without clearing the format and removing the <divs> (which don't act the same as just normal spacing)
