### ISSUE TITLE
Google Analytics - Page Count Discrepancy

### ISSUE THREAD

**Issue by JoannaIHC** [600lines/iheartcomix#43]
In the "All Pages" tracking under Behavior>Site Content>All Pages
When I do a search for Heems, the traffic looks like it's getting separated into individual links that go about 5 pages deep each with 1 pageview

When you look at the most popular pages Heems has 83 views but added up it says 201? Really confused about what this means - can you investigate?

![screen shot 2015-05-27 at 11 26 08 am](https://cloud.githubusercontent.com/assets/10623537/7844175/64b84f5e-0463-11e5-8f38-66793d472ae9.png)

**Comment by 600lines** [comment]
Mailchimp referrals
